### ISSUE TITLE
Starter tutorial for custom application

### ISSUE THREAD

**Issue by ArneOb** [totaljs/openplatform#10]
Hi,
could you please provide more precise informations about how to start building custom applications?
E.g.  where shall they live etc.; the configuration is quite clear.
That would be great!
Kind regards
_____
Arne

**Comment by petersirka** [comment]
Hi @ArneOb, 
it's my plan...

__How to start now?__
- first you need a domain
- download and run OpenPlatform on this domain
- second you need the second domain for som app
- download app example
- run it and add it to openplatform

I want to create more apps and video tutorial with getting started.
