### ISSUE TITLE
X-Frame-Options sameorigin

### ISSUE THREAD

**Issue by hektor157** [totaljs/openplatform#11]
Ahoy.

Any ideas how to bypass X-Frame-Options sameorigin, 
other than disabling it on destination server?

Thanks

**Comment by petersirka** [comment]
Hi @hektor157,
you need to disable it on destination server... I think that this is the only way....

**Comment by hektor157** [comment]
As I thought

**Comment by Teutone** [comment]
You could also replace the header completely with the more flexible CSP header frame-ancestors

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors
