### ISSUE TITLE
Cannot login with default credentials

### ISSUE THREAD

**Issue by vasopikof** [totaljs/openplatform#12]
at ccdb22f

test at clean dockerized environment

openplatform    | --------> DEBUG PID: 1 (v3.0.0)
openplatform    | ====================================================
openplatform    | PID           : 13
openplatform    | Node.js       : v10.10.0
openplatform    | Total.js      : v3.0.0
openplatform    | OS            : linux 4.4.0-96-generic
openplatform    | Memory        : 12.51 MB / 20.35 MB
openplatform    | ====================================================
openplatform    | Name          : OpenPlatform v3
openplatform    | Version       : 3.0.0
openplatform    | Author        : undefined
openplatform    | Date          : 2018-09-10 15:07:26
openplatform    | Mode          : debug
openplatform    | ====================================================
openplatform    | Directory     : /usr/src/app
openplatform    | node_modules  : /usr/src/app/node_modules/total.js/
openplatform    | ====================================================
openplatform    |
openplatform    | http://0.0.0.0:80/
openplatform    |
openplatform    | ======= 2018-09-10 15:10:41: api ---> TypeError: Cannot read property 'decrypt' of undefined (http://ip172-18-0-93-beb8e3bt07tg009dvgi0-80.direct.labs.play-with-docker.com/api/users/) TypeError: Cannot read property 'decrypt' of undefined
openplatform    |     at Object.OP.decodeAuthToken (/usr/src/app/definitions/openplatform.js:179:14)
openplatform    |     at SchemaBuilderEntity.onQuery (/usr/src/app/schemas/users.js:42:16)
openplatform    |     at SchemaBuilderEntity.query (/usr/src/app/node_modules/total.js/builders.js:1390:9)
openplatform    |     at Controller.$query (/usr/src/app/node_modules/total.js/index.js:9927:19)
openplatform    |     at Controller.controller_json_workflow (/usr/src/app/node_modules/total.js/index.js:16576:17)
openplatform    |     at IncomingMessage.PROTO.$total_execute2 (/usr/src/app/node_modules/total.js/index.js:14505:32)
openplatform    |     at IncomingMessage.PROTO.$total_execute (/usr/src/app/node_modules/total.js/index.js:14473:9)
openplatform    |     at IncomingMessage.PROTO.$total_authorize (/usr/src/app/node_modules/total.js/index.js:14592:10)
openplatform    |     at /usr/src/app/node_modules/total.js/index.js:14760:9
openplatform    |     at Framework.onAuthorize (/usr/src/app/definitions/auth.js:27:10)
openplatform    | ======= 2018-09-10 15:15:50: api ---> TypeError: Cannot read property 'decrypt' of undefined (http://ip172-18-0-93-beb8e3bt07tg009dvgi0-80.direct.labs.play-with-docker.com/api/users/) TypeError: Cannot read property 'decrypt' of undefined
openplatform    |     at Object.OP.decodeAuthToken (/usr/src/app/definitions/openplatform.js:179:14)
openplatform    |     at SchemaBuilderEntity.onQuery (/usr/src/app/schemas/users.js:42:16)
openplatform    |     at SchemaBuilderEntity.query (/usr/src/app/node_modules/total.js/builders.js:1390:9)
openplatform    |     at Controller.$query (/usr/src/app/node_modules/total.js/index.js:9927:19)
openplatform    |     at Controller.controller_json_workflow (/usr/src/app/node_modules/total.js/index.js:16576:17)
openplatform    |     at IncomingMessage.PROTO.$total_execute2 (/usr/src/app/node_modules/total.js/index.js:14505:32)
openplatform    |     at IncomingMessage.PROTO.$total_execute (/usr/src/app/node_modules/total.js/index.js:14473:9)
openplatform    |     at IncomingMessage.PROTO.$total_authorize (/usr/src/app/node_modules/total.js/index.js:14592:10)
openplatform    |     at /usr/src/app/node_modules/total.js/index.js:14760:9
openplatform    |     at Framework.onAuthorize (/usr/src/app/definitions/auth.js:27:10)

**Comment by petersirka** [comment]
I have same problem. I'll fix it today.

**Comment by petersirka** [comment]
Hi, I have fixed it. There were two problems:

- auth cookie was only for `https`
- and I have fixed with token decoding

Download the source-code again or download `openplatform.bundle` only.
Thank you!
