### ISSUE TITLE
Seriously, great work, but some minor implementation issues... 

### ISSUE THREAD

**Issue by rwdim** [totaljs/openplatform#19]
### "value && value.items.length" is bad and is throwing errors.. **in users-grid.html**

Everywhere this kind of check is used should be replaced with 

```
values && Array.isArray( value.items ) ....
```

Current code assumes values is never null,  and also that items is always a non-null array.

Also, in admin.html, this code fails when value is null.. there's no check...
```
	Thelpers.groups = function(value) {

		if (!value.length)
			return '';
```

<img width="905" alt="Screen Shot 2019-10-25 at 12 02 52 PM" src="https://user-images.githubusercontent.com/416537/67590028-8c376c00-f71f-11e9-90fc-5f5b5373f008.png">

**Comment by petersirka** [comment]
Hmmm, value can't be null. Can you check server-side logs in terminal? Or can you send me the response from the server?

**Comment by rwdim** [comment]
Will do.

**Comment by rwdim** [comment]
Ok... it looks like you're developing in your master branch?, so I checked out v4.1.0 and it works as expected. 

Not as pretty, but it seems to work.  Clean checkout of master throws numerous errors when viewing the user list... /api/op/users/  generates an error response in json stating that _column 'note' does not exist._

I'll play with v4.1 for now... thx :)

**Comment by petersirka** [comment]
On our end, it was an eternity instead of a delay. We prepared a brand-new version that includes all of the fixes. Really sorry.
