### ISSUE TITLE
How to make another view like Applications

### ISSUE THREAD

**Issue by ameykshirsagar** [totaljs/openplatform#2]
I am trying to build a platform maintenance console using Open Platform but I am not able to add another view to top level view along with Applications & Users.
Can I get a short explanation of how to do that??

Thanks

**Comment by petersirka** [comment]
Hi @ameykshirsagar,
you want to add a new item into the navigation?

Here you can add your new item:
<https://github.com/totaljs/openplatform/blob/master/views/index.html#L33>

And here you can create routing:
<https://github.com/totaljs/openplatform/blob/master/views/index.html#L79>

BTW: but I don't know whether you understand. Create a console as application for OpenPlatform, here is example: <https://github.com/totaljs/openplatform-application>.

Or try to create realtime-chat like this: <https://github.com/fokinko/openplatform-sample-chat>

Thank you!

**Comment by ameykshirsagar** [comment]
Hi @petersirka 
What openplatform is doing is great but I was expecting to add a top level entity along with Applications that can create different applications like entities.
I shall close this issue right away.
Thank you for your guidance.
