### ISSUE TITLE
Port all the databases to a better tech

### ISSUE THREAD

**Issue by ameykshirsagar** [totaljs/openplatform#3]
How can I port the internal database of open platform from file based JSON storage to a better one like MongoDB??

Thanks

**Comment by petersirka** [comment]
Hi @ameykshirsagar,
I think that it's not a problem. But users must be read into the memory.

__Just update:__

1. save users
https://github.com/totaljs/openplatform/blob/master/definitions/openplatform.js#L55

2. load users
https://github.com/totaljs/openplatform/blob/master/definitions/openplatform.js#L71

But you have to update applications and settings too. It's not complicated.
Thank you!

**Comment by ameykshirsagar** [comment]
@petersirka : I tried the mongoose utilisation and so far I am able to do basic auth & users CRUD. But the notify part isn't working as it should.

**Comment by petersirka** [comment]
Did you mean notifications?
If yes then update only two methods:

`User.prototype.getNotifications`:
https://github.com/totaljs/openplatform/blob/master/models/model-user.js#L77

`User.prototype.notify`:
https://github.com/totaljs/openplatform/blob/master/models/model-user.js#L107

It should work.

**Comment by ameykshirsagar** [comment]
Alright cool. Thanks a lot @petersirka
