### ISSUE TITLE
Email is not working

### ISSUE THREAD

**Issue by backendbox** [totaljs/openplatform#5]
Try to notify users in group, but don't receive any email. Already setup smtp config

**Comment by molda** [comment]
Hi, there was a change in naming of smtp props
From `mail.smtp` to `mail-smtp` etc.
https://docs.totaljs.com/latest/en.html#api~FrameworkConfiguration~mail-smtp

Are you using correct format?

**Comment by petersirka** [comment]
@backendbox I have fixed it.... @molda my mistake: https://github.com/totaljs/openplatform/commit/7d992f550802a0987a88b27538f1107acd992e04

**Comment by backendbox** [comment]
======= 2017-05-18 19:12:16: internal ---> TypeError: Cannot read property 'leng
th' of undefined (http://*/internal/users/newsletter/)
 TypeError: Cannot read property 'length' of undefined

How about this?

**Comment by petersirka** [comment]
Omg, my mistake again.
I have fixed all bugs with mail + I have tested it and everything works correctly now.

Thank you and sorry.
