### ISSUE TITLE
[Security] Stored XSS in account name

### ISSUE THREAD

**Issue by edoardottt** [totaljs/openplatform#52]
Tested version: [b80b09d](https://github.com/totaljs/openplatform/commit/b80b09d1e12ada675d0cbb6d9c4af9e5a8097751) (latest)

Steps to reproduce the vulnerability:

- Login in the application.
- Click on user profile picture in the right corner below.
- Click My Account
- Set `"><img src=x onerror=alert(document.domain)>` as account name and save.
- XSS fires.
- Each time a target will visit the dashboard the payload will fire, even if the target is not logged in! In order to test this, just click logout and reload the page.

![poc1](https://user-images.githubusercontent.com/35783570/219962334-712f0352-c9c5-47f3-8401-82a877f39826.png)

![poc2](https://user-images.githubusercontent.com/35783570/219962337-b083e414-c380-445b-8b24-3f8aeab4b4a3.png)

**Comment by Gera-IC** [comment]
Thank you, I already fixed it in my own adding .removeTags(); but I think there are better ways as ui-bind, validator, etc.. this is the easy fix. :)

<img width="490" alt="Captura de pantalla 2023-02-19 a las 20 00 53" src="https://user-images.githubusercontent.com/57091288/219969318-9997a7e4-0a01-4051-9fb2-ef5cbff06fa6.png">

**Comment by edoardottt** [comment]
don't rely on these naive solutions, there are specific libraries to sanitize input. you can use symbols in fields but simply they will be rendered as pure text and not html.

**Comment by Gera-IC** [comment]
You right. Thank you so much... im trying different solutions thanks to your observation... :)

**Comment by petersirka** [comment]
@edoardottt fixed https://github.com/totaljs/openplatform/commit/b6a128a5cc130394ca8c397db01a6e53b64c0948.
