### ISSUE TITLE
add event listener to ESC key to close windows

### ISSUE THREAD

**Issue by landsman** [totaljs/openplatform#58]
It's frustrating that I can not close windows by pressing the ESC key. 
Please add an event listener for that. 🙏

**Comment by landsman** [comment]
btw here is great standard which you can probably use, to make it work out of the box: https://blog.webdevsimplified.com/2023-04/html-dialog/

**Comment by petersirka** [comment]
It depends on which modal forms because if you fill a form and press the ESC key accidentally, your data will be lost. Therefore we disabled this functionality.

**Comment by landsman** [comment]
> It depends on which modal forms because if you fill a form and press the ESC key accidentally, your data will be lost. Therefore we disabled this functionality.

Okay, I understand. Anyway, you can do `confirm()` dialog if data was modified and not saved yet. Or save them to localStorage, for easy recovery, as many platforms do.

**Comment by petersirka** [comment]
Yes, but it's not easy to implement it thoroughly. We will add notes about it to our to-do list for future implementation. Try to find a smart solution for all forms and make a pull request if you need it ASAP. We will consider approving.
