### ISSUE TITLE
Add users programmatically

### ISSUE THREAD

**Issue by Yakito** [totaljs/openplatform#60]
Hi! Is currently possible to add users programmatically via API?
Thanks!

**Comment by petersirka** [comment]
Hi. You have many ways how to do it, for example:

1) insert users directly into the DB
2) create a small chunk of code for inserting users
3) create public API route e.g. `ROUTE('POST /internal/users/  *Users  --> create);` and then you must send JSON payload with this structure: https://github.com/totaljs/openplatform/blob/master/plugins/setup/schemas/users.js

**Comment by petersirka** [comment]
I have added a support for it:

![20230915-234217](https://github.com/totaljs/openplatform/assets/2414252/95ec78aa-d97e-489c-8e6f-14471c2913d0)

---

**Commit:**
[Added an option to enable native scrollbars in iframes.](https://github.com/totaljs/openplatform/commit/feb471ad812f4d1529d69eebd2d2a6f630968bcb)

---

Just update bundle and run this SQL script in your DB:
https://github.com/totaljs/openplatform/blob/master/database-2023-09-15.sql
