### ISSUE TITLE
OpenPlatform + Flow, user accounts

### ISSUE THREAD

**Issue by bohtho** [totaljs/openplatform#74]
It's probably my own fault, but I have an issue with syncing and access between OpenPlatform and Flow.

I first installed Flow by a docker compose, logged in and changed the username and password, and started making a flow.

Then I added OpenPlatform to the docker compose file, changed the admin account there too, and imported my Flow app as an app in OpenPlatform, including registering the request and response tokens to the Flow settings.

It makes sense that I no longer can access the Flow app directly, and my admin account can use Flow via OpenPlatform, and see the same flow there as built earlier.

But if I make another user account in OpenPlatform, in a group which has all access rights to the Flow app, all I see of the Flow app is the top left "hamburger menu", and the bug and the magnifying glass in the top left, but none are responsive.

I've tried the "synchronize" button in the app settings as well as reloading and logging in and out. Isn't a new user in OpenPlatform supposed to be messaged to any imported apps, which then opens a new local account and workspace for them ? If this is related to me starting to use Flow before adding OpenPlatform, how do I reset this behaviour ?

**Comment by petersirka** [comment]
Thank you. There was a bug in the Flow :-/ ... 

**It's fixed:**
https://github.com/totaljs/flow/commit/d7209cd27577eef79c7465ffc5ec889f6ec9eccf

You need to update the Flow app. If you use a bundled version, then download the Flow bundle (+ restart app) or update a Docker image + restart container.

- Flow bundle <https://github.com/totaljs/flow/tree/master/--bundles-->

**Comment by petersirka** [comment]
> I've tried the "synchronize" button in the app settings as well as reloading and logging in and out. Isn't a new user in OpenPlatform supposed to be messaged to any imported apps, which then opens a new local account and workspace for them ? If this is related to me starting to use Flow before adding OpenPlatform, how do I reset this behaviour ?

The OpenPlatform manages users and their permissions to third-party apps. The other functionality depends on the app. The OpenPlatform doesn't notify apps when a user is created, updated, or removed. This logic must be provided in the app directly. Or the app can be connected to the OpenPlatform API or database and watch changes.

**How to reset the Flow with the OP?** Only admins can open Flow and remove the request token and response token from the Flow settings. After that, the Flow will work as before.
