### ISSUE TITLE
Loading gif issue !

### ISSUE THREAD

**Issue by backendbox** [totaljs/openplatform#8]
<img width="456" alt="screen shot 2017-05-26 at 9 28 10 pm" src="https://cloud.githubusercontent.com/assets/14541106/26498750/4b5e14ee-425a-11e7-9ca0-c2395248c712.png">

Loading gif stuck ? How to fix it ?

P/s : I think the url endpoint is working behind HA Proxy !

**Comment by petersirka** [comment]
Please open a web console in your web browser and check an error. Give me a feedback

**Comment by backendbox** [comment]
@petersirka Hello, I already send you access to my openplatform server via your email, please help me check !

**Comment by petersirka** [comment]
- __loading__: just set a background :-D on `body` (iframe can be transparent too)
- __scrolling__: set `height:100%` to your container `div`

![Solution for a problem](https://cloud.githubusercontent.com/assets/2414252/26502285/8daece92-423c-11e7-9f4f-5f1425519f8c.png)

Thank you!

**Comment by backendbox** [comment]
Great, Thank you so much @petersirka
