### ISSUE TITLE
Unable to hit api behind proxy

### ISSUE THREAD

**Issue by kuproydev** [totaljs/openplatform#84]
Hi there,
I'm new to total.js
I just installed the app and it works fine, but after proxying, the app doesn't work as it should be. 
i'm proxy at domain.com/openplatform/
after the proxy app hit **domain.com/api/login** it should be **domain.com/openplatform/api/login**
Is there a way to set the base url in the app? 

Thank you!

**Comment by petersirka** [comment]
Hello,
This is not possible yet. OpenPlatform must run as the root app of a domain. So, you can provide OpenPlatform like:

- `openplatform.domain.com` instead of `domain.com/openplatform`

**Comment by kuproydev** [comment]
Hi, 
Thank you for fast response & your suggestion.
Hopefully one day there will be this feature😁.
