### ISSUE TITLE
Stuck in the landing page, no progress, page resets after 10 seconds

### ISSUE THREAD

**Issue by dryuvrajk** [totaljs/openplatform#86]
I have started the instance as instructed and then opened a localhost:8000 tab.

The page loads but loops 1-10 seconds and then resets back to 1-10. The data base field shows database only. No progress. The database with OpenPlatform is created and is assigned to the group, all parameters intact.

Images:

![image](https://github.com/totaljs/openplatform/assets/5370661/3fac4219-b17b-436d-abbc-b3deb10f4923)

![image](https://github.com/totaljs/openplatform/assets/5370661/1f54732a-45af-4a8a-b974-fcb5dee420aa)

![image](https://github.com/totaljs/openplatform/assets/5370661/da59280a-d9e0-48a8-9c33-707d0cb27f54)

![image](https://github.com/totaljs/openplatform/assets/5370661/cc4f480f-0c31-4fcd-98d3-7948508d0a33)

What could be wrong?

**Comment by Gera-G-Guiles** [comment]
Your application is waiting for database connection, check you connection string in your config file, database name, etc...
Also you are using 2 connections strings, so choose only one database or database (env). 
note: (env) load variable from environment

**Comment by swaminathan33** [comment]
Hi, I am also having the same issue. was it resolved? i checked everything.
