### ISSUE TITLE
404 image not found johndeal_domain_com.jpg

### ISSUE THREAD

**Issue by SadiqUltra** [totaljs/openplatform#9]
In the home page of openplatform, I am getting a 404 error of this image johndeal_domain_com.jpg.
It should point to http://DOMAIN.COM/photos/johndeal_domain_com.jpg instead of
http://127.0.0.1:8000/photos/johndeal_domain_com.jpg

Thanks.

**Comment by tomee03** [comment]
Hi... and where you have saved image? You have image saved in /public/photos folder? Thanks

**Comment by molda** [comment]
Hi try to change the url in config file to your domain
`url  : http://127.0.0.1:8000` -> `url  :  http://DOMAIN.COM`

**Comment by petersirka** [comment]
@SadiqUltra open `Settings` page and set the URL there. I use OpenPlatform in production and everything works correctly.

**Comment by SadiqUltra** [comment]
Working
